# Snakemake test file
# -------------------
# Author: Thomas Schwarzl <schwarzl@embl.de>
# Licence: MIT
# -------------------
# "snakemake mktest" - creates test examples
#   -> A.in.txt
#   -> B.in.txt
# -------------------
# "snakemake" - creates output
#   -> stats.txt
# ------------------
# "snakemake clean"
#    removes all *txt and *log files
# ------------------

SAMPLES="A B".split()

# ===================

rule all:
  input:
    "stats.txt"

rule stats:
  input:
    expand("{sample}.in.txt", sample=SAMPLES)
  output:
    "stats.txt"
  message:
    "creating statistics - {output}"
  log:
    "stats.log"
  shell:
    "head {input} > {output} 2> {log}"

rule mktest:
  input: 
    expand("{samples}.in.txt", samples=SAMPLES)

rule do_mktest:
  output:
    "{file}.in.txt"
  message:
    "creating the test file {output}"
  shell:
   "echo '{wildcards.file}' > {output}"

rule clean:
  message:
    "cleaning up directory"
  shell:
    "rm *txt *log"
